In [1]:
library(twang)
library(weights)
library(Matching)
library(tidyverse)

Loading required package: gbm
Loading required package: survival
Loading required package: lattice
Loading required package: splines
Loading required package: parallel
Loaded gbm 2.1.3
Loading required package: survey
Loading required package: grid
Loading required package: Matrix

Attaching package: ‘survey’

The following object is masked from ‘package:graphics’:

    dotchart

Loading required package: xtable
Loading required package: latticeExtra
Loading required package: RColorBrewer
Loading required package: Hmisc
Loading required package: Formula
Loading required package: ggplot2

Attaching package: ‘ggplot2’

The following object is masked from ‘package:latticeExtra’:

    layer


Attaching package: ‘Hmisc’

The following objects are masked from ‘package:xtable’:

    label, label<-

The following object is masked from ‘package:survey’:

    deff

The following objects are masked from ‘package:base’:

    format.pval, units

Loading required package: gdata
gdata: read.xls support for 'XLS' (Excel 97-2004) files ENABLED.

gdata: read.xls support for 'XLSX' (Excel 2007+) files ENABLED.

Attaching package: ‘gdata’

The following object is masked from ‘package:stats’:

    nobs

The following object is masked from ‘package:utils’:

    object.size

The following object is masked from ‘package:base’:

    startsWith

Loading required package: mice
Loading required package: MASS
##
##  Matching (Version 4.9-2, Build Date: 2015-12-25)
##  See http://sekhon.berkeley.edu/matching for additional documentation.
##  Please cite software as:
##   Jasjeet S. Sekhon. 2011. ``Multivariate and Propensity Score Matching
##   Software with Automated Balance Optimization: The Matching package for R.''
##   Journal of Statistical Software, 42(7): 1-52.
##

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ tibble  1.4.2     ✔ purrr   0.2.4
✔ tidyr   0.8.0     ✔ dplyr   0.7.4
✔ readr   1.1.1     ✔ stringr 1.2.0
✔ tibble  1.4.2     ✔ forcats 0.2.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::combine()   masks gdata::combine()
✖ tidyr::complete()  masks mice::complete()
✖ tidyr::expand()    masks Matrix::expand()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::first()     masks gdata::first()
✖ purrr::keep()      masks gdata::keep()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::last()      masks gdata::last()
✖ ggplot2::layer()   masks latticeExtra::layer()
✖ dplyr::select()    masks MASS::select()
✖ dplyr::src()       masks Hmisc::src()
✖ dplyr::summarize() masks Hmisc::summarize()

In [2]:
data_dir <- file.path("..", "data")

In [3]:
full_data <- readRDS(file.path(data_dir, "full_data_ps.rds"))
head(full_data)

  icustay_id hadm_id subject_id first_careunit intime
1 228416     159895   5491      MICU           2151-06-29 01:18:27
2 278148     169700  49395      MICU           2197-01-09 00:45:42
3 274174     103722  14855      MICU           2181-09-08 23:43:13
4 214954     170515  54642      MICU           2176-03-11 04:58:23
5 222457     183493  96815      MICU           2105-06-04 20:57:55
6 264413     134244  81436      MICU           2133-03-27 16:31:37
  outtime             angus age      icu_order echo_time  ⋯ lab_pco2_flag
1 2151-07-27 16:00:56 1     76.58225 1         2151-06-30 ⋯ 1
2 2197-01-10 06:46:29 1     82.72606 1         <NA>       ⋯ 0
3 2181-09-26 16:52:02 1     61.84390 1         2181-09-11 ⋯ 1
4 2176-03-15 18:00:48 1     63.86507 1         2176-03-11 ⋯ 1
5 2105-06-06 20:01:51 1     62.84018 1         <NA>       ⋯ 0
6 2133-04-04 16:15:28 1     62.60148 1         2133-03-31 ⋯ 0
  lab_creatinine_flag lab_potassium_flag lab_troponin_flag lab_po2_flag
1 1                   1                  0                 1
2 1                   1                  0                 0
3 1                   1                  0                 1
4 1                   1                  1                 1
5 1                   1                  0                 0
6 1                   1                  0                 0
  lab_lactate_flag echo_int mort_28_day_int ps        ps_weight
1 1                1        0               0.5525232 1.809879
2 0                0        1               0.2804613 1.389779
3 1                1        0               0.3012020 3.320031
4 1                1        0               0.7982833 1.252688
5 0                0        0               0.2244447 1.289399
6 1                1        0               0.3320492 3.011602

In [4]:
library(tableone)

In [5]:
features <- c("age", "gender", "first_careunit", "weight",
              "saps", "sofa", "elix_score", "vent", "vaso", "sedative",
              "icd_chf", "icd_afib", "icd_renal", "icd_liver",
              "icd_copd", "icd_cad", "icd_stroke", "icd_malignancy",
              "icu_adm_weekday", "icu_adm_hour",
              "vs_map_first", "vs_heart_rate_first", "vs_temp_first", "vs_cvp_first",
              "lab_wbc_first", "lab_hemoglobin_first", "lab_platelet_first",
              "lab_sodium_first", "lab_potassium_first", "lab_bicarbonate_first",
              "lab_chloride_first", "lab_bun_first", "lab_lactate_first",
              "lab_creatinine_first", "lab_ph_first", "lab_po2_first", "lab_pco2_first",
              "lab_bnp_flag", "lab_troponin_flag", "lab_creatinine_kinase_flag")

In [6]:
tab <- CreateTableOne(vars = features,
                      strata = "echo",
                      data = full_data,
                      argsNormal = list(var.equal = FALSE))
capture.output(tab_df <- tab %>%
               print(smd = TRUE) %>%
               as.data.frame(stringsAsFactors = FALSE) %>%
               select(-test)) %>% invisible

In [7]:
tab_df

                                   0               1               p
n                                    3099            3262
age (mean (sd))                     66.69 (17.21)   65.74 (16.55)   0.026
gender = F (%)                       1575 (50.8)     1558 (47.8)    0.016
first_careunit = MICU (%)            2404 (77.6)     2593 (79.5)    0.067
weight (mean (sd))                  78.56 (23.58)   83.17 (26.87)  <0.001
saps (mean (sd))                    19.63 (5.79)    20.76 (5.44)   <0.001
sofa (mean (sd))                     5.31 (3.62)     6.33 (3.79)   <0.001
elix_score (mean (sd))               8.51 (7.45)    10.07 (7.67)   <0.001
vent = 1 (%)                         1459 (47.1)     1901 (58.3)   <0.001
vaso = 1 (%)                          839 (27.1)     1228 (37.6)   <0.001
sedative = 1 (%)                     1247 (40.2)     1623 (49.8)   <0.001
icd_chf = 1 (%)                       563 (18.2)     1304 (40.0)   <0.001
icd_afib = 1 (%)                      622 (20.1)     1056 (32.4)   <0.001
icd_renal = 1 (%)                     436 (14.1)      536 (16.4)    0.010
icd_liver = 1 (%)                     314 (10.1)      365 (11.2)    0.185
icd_copd = 1 (%)                      470 (15.2)      571 (17.5)    0.013
icd_cad = 1 (%)                       369 (11.9)      515 (15.8)   <0.001
icd_stroke = 1 (%)                    240 ( 7.7)      353 (10.8)   <0.001
icd_malignancy = 1 (%)                782 (25.2)      729 (22.3)    0.008
icu_adm_weekday (%)                                                <0.001
   sunday                             393 (12.7)      462 (14.2)
   monday                             416 (13.4)      476 (14.6)
   tuesday                            427 (13.8)      494 (15.1)
   wednesday                          423 (13.6)      514 (15.8)
   thursday                           464 (15.0)      499 (15.3)
   friday                             538 (17.4)      446 (13.7)
   saturday                           438 (14.1)      371 (11.4)
icu_adm_hour (%)                                                    0.356
   0                                  139 ( 4.5)      146 ( 4.5)
   1                                  117 ( 3.8)      122 ( 3.7)
⋮                                  ⋮               ⋮               ⋮
   14                                 142 ( 4.6)      157 ( 4.8)
   15                                 133 ( 4.3)      150 ( 4.6)
   16                                 201 ( 6.5)      171 ( 5.2)
   17                                 205 ( 6.6)      188 ( 5.8)
   18                                 223 ( 7.2)      232 ( 7.1)
   19                                 196 ( 6.3)      205 ( 6.3)
   20                                 237 ( 7.6)      240 ( 7.4)
   21                                 216 ( 7.0)      224 ( 6.9)
   22                                 205 ( 6.6)      234 ( 7.2)
   23                                 195 ( 6.3)      173 ( 5.3)
vs_map_first (mean (sd))            79.91 (19.44)   80.03 (20.48)   0.809
vs_heart_rate_first (mean (sd))     93.01 (19.81)   95.07 (21.79)  <0.001
vs_temp_first (mean (sd))           36.75 (1.05)    36.85 (1.90)    0.005
vs_cvp_first (mean (sd))            11.88 (17.09)   13.74 (20.45)   0.019
lab_wbc_first (mean (sd))           13.48 (14.03)   13.76 (12.41)   0.403
lab_hemoglobin_first (mean (sd))    10.55 (1.98)    10.60 (2.04)    0.406
lab_platelet_first (mean (sd))     223.96 (134.79) 211.55 (128.46) <0.001
lab_sodium_first (mean (sd))       139.09 (6.45)   138.56 (5.89)    0.001
lab_potassium_first (mean (sd))      4.10 (0.79)     4.15 (0.84)    0.017
lab_bicarbonate_first (mean (sd))   22.28 (5.40)    22.35 (5.71)    0.624
lab_chloride_first (mean (sd))     106.21 (7.45)   105.14 (7.20)   <0.001
lab_bun_first (mean (sd))           32.02 (26.34)   36.01 (27.38)  <0.001
lab_lactate_first (mean (sd))        2.62 (2.35)     2.51 (2.27)    0.143
lab_creatinine_first (mean (sd))     1.60 (1.66)     1.83 (1.81)   <0.001
lab_ph_first (mean (sd))             7.35 (0.11)     7.34 (0.11)    0.160
lab_po2_first (mean (sd))          147.61 (107.49) 133.24 (93.89)  <0.001
lab_pco2_first (mean (sd))          41.48 (13.34)   42.77 (14.83)   0.003
lab_bnp_flag = 1 (%)                   37 ( 1.2)      144 ( 4.4)   <0.001
lab_troponin_flag = 1 (%)             633 (20.4)     1327 (40.7)   <0.001
lab_creatinine_kinase_flag = 1 (%)   1154 (37.2)     1934 (59.3)   <0.001
                                   SMD
n
age (mean (sd))                     0.056
gender = F (%)                      0.061
first_careunit = MICU (%)           0.047
weight (mean (sd))                  0.182
saps (mean (sd))                    0.202
sofa (mean (sd))                    0.277
elix_score (mean (sd))              0.207
vent = 1 (%)                        0.226
vaso = 1 (%)                        0.227
sedative = 1 (%)                    0.192
icd_chf = 1 (%)                     0.495
icd_afib = 1 (%)                    0.282
icd_renal = 1 (%)                   0.066
icd_liver = 1 (%)                   0.034
icd_copd = 1 (%)                    0.063
icd_cad = 1 (%)                     0.113
icd_stroke = 1 (%)                  0.106
icd_malignancy = 1 (%)              0.068
icu_adm_weekday (%)                 0.148
   sunday
   monday
   tuesday
   wednesday
   thursday
   friday
   saturday
icu_adm_hour (%)                    0.125
   0
   1
⋮                                  ⋮
   14
   15
   16
   17
   18
   19
   20
   21
   22
   23
vs_map_first (mean (sd))            0.006
vs_heart_rate_first (mean (sd))     0.099
vs_temp_first (mean (sd))           0.070
vs_cvp_first (mean (sd))            0.099
lab_wbc_first (mean (sd))           0.021
lab_hemoglobin_first (mean (sd))    0.021
lab_platelet_first (mean (sd))      0.094
lab_sodium_first (mean (sd))        0.086
lab_potassium_first (mean (sd))     0.061
lab_bicarbonate_first (mean (sd))   0.012
lab_chloride_first (mean (sd))      0.145
lab_bun_first (mean (sd))           0.149
lab_lactate_first (mean (sd))       0.047
lab_creatinine_first (mean (sd))    0.132
lab_ph_first (mean (sd))            0.043
lab_po2_first (mean (sd))           0.142
lab_pco2_first (mean (sd))          0.091
lab_bnp_flag = 1 (%)                0.196
lab_troponin_flag = 1 (%)           0.451
lab_creatinine_kinase_flag = 1 (%)  0.452

In [8]:
ipw_svydesign <- readRDS(file.path(data_dir, "ipw_svydesign.rds"))

In [9]:
tab_wtd <- svyCreateTableOne(vars = features,
                             strata = "echo",
                             data = ipw_svydesign)

In [10]:
capture.output(tab_wtd_df <- tab_wtd %>%
               print %>%
               as.data.frame(stringsAsFactors = FALSE) %>%
               select(-test)) %>% invisible

In [11]:
tab_wtd_df

                                   0                1                p
n                                  5739.48          5842.36
age (mean (sd))                      65.93 (16.29)    65.15 (16.73)   0.076
gender = F (%)                      2824.2 (49.2)    2824.0 (48.3)    0.523
first_careunit = MICU (%)           4473.6 (77.9)    4641.0 (79.4)    0.178
weight (mean (sd))                   82.31 (23.50)    83.50 (25.25)   0.163
saps (mean (sd))                     23.13 (5.60)     23.41 (5.18)    0.134
sofa (mean (sd))                      8.25 (4.25)      8.52 (3.79)    0.038
elix_score (mean (sd))               10.19 (7.45)     10.02 (7.81)    0.114
vent = 1 (%)                        2907.8 (50.7)    3139.0 (53.7)    0.025
vaso = 1 (%)                        1759.7 (30.7)    1965.5 (33.6)    0.020
sedative = 1 (%)                    2467.6 (43.0)    2683.2 (45.9)    0.030
icd_chf = 1 (%)                     1499.2 (26.1)    1816.5 (31.1)   <0.001
icd_afib = 1 (%)                    1443.7 (25.2)    1644.1 (28.1)    0.015
icd_renal = 1 (%)                    905.2 (15.8)     900.6 (15.4)    0.725
icd_liver = 1 (%)                    604.1 (10.5)     651.2 (11.1)    0.465
icd_copd = 1 (%)                     940.0 (16.4)     996.3 (17.1)    0.511
icd_cad = 1 (%)                      765.5 (13.3)     859.4 (14.7)    0.155
icd_stroke = 1 (%)                   497.4 ( 8.7)     578.3 ( 9.9)    0.126
icd_malignancy = 1 (%)              1425.3 (24.8)    1399.2 (23.9)    0.457
icu_adm_weekday (%)                                                   0.585
   sunday                            760.2 (13.2)     798.6 (13.7)
   monday                            770.4 (13.4)     805.3 (13.8)
   tuesday                           801.4 (14.0)     883.3 (15.1)
   wednesday                         838.6 (14.6)     876.7 (15.0)
   thursday                          859.3 (15.0)     873.4 (14.9)
   friday                            933.1 (16.3)     903.8 (15.5)
   saturday                          776.6 (13.5)     701.2 (12.0)
icu_adm_hour (%)                                                      1.000
   0                                 268.5 ( 4.7)     268.6 ( 4.6)
   1                                 215.3 ( 3.8)     227.0 ( 3.9)
⋮                                  ⋮                ⋮                ⋮
   14                                255.6 ( 4.5)     271.6 ( 4.6)
   15                                248.1 ( 4.3)     266.4 ( 4.6)
   16                                358.4 ( 6.2)     338.6 ( 5.8)
   17                                365.2 ( 6.4)     352.1 ( 6.0)
   18                                402.8 ( 7.0)     416.1 ( 7.1)
   19                                362.6 ( 6.3)     377.4 ( 6.5)
   20                                431.4 ( 7.5)     427.5 ( 7.3)
   21                                393.6 ( 6.9)     398.9 ( 6.8)
   22                                396.5 ( 6.9)     411.8 ( 7.0)
   23                                344.9 ( 6.0)     329.9 ( 5.6)
vs_map_first (mean (sd))             77.49 (21.82)    76.51 (20.07)   0.894
vs_heart_rate_first (mean (sd))      99.98 (21.81)    99.77 (22.28)   0.327
vs_temp_first (mean (sd))            36.77 (1.26)     36.79 (2.19)    0.151
vs_cvp_first (mean (sd))             12.66 (19.04)    13.97 (20.79)   0.082
lab_wbc_first (mean (sd))            15.02 (12.82)    15.33 (11.24)   0.900
lab_hemoglobin_first (mean (sd))     10.54 (2.02)     10.52 (2.03)    0.798
lab_platelet_first (mean (sd))      220.31 (138.50)  215.24 (137.67)  0.375
lab_sodium_first (mean (sd))        138.39 (6.18)    138.91 (5.71)    0.110
lab_potassium_first (mean (sd))       4.16 (0.83)      4.18 (0.92)    0.490
lab_bicarbonate_first (mean (sd))    20.28 (5.19)     20.34 (5.74)    0.901
lab_chloride_first (mean (sd))      106.56 (7.56)    106.88 (7.19)    0.034
lab_bun_first (mean (sd))            36.07 (24.45)    39.08 (28.74)   0.177
lab_lactate_first (mean (sd))         3.03 (2.60)      2.89 (2.59)    0.321
lab_creatinine_first (mean (sd))      1.81 (1.37)      1.91 (1.64)    0.122
lab_ph_first (mean (sd))              7.32 (0.11)      7.31 (0.11)    0.904
lab_po2_first (mean (sd))           142.46 (105.66)  135.09 (97.34)   0.166
lab_pco2_first (mean (sd))           40.43 (12.57)    41.09 (13.21)   0.481
lab_bnp_flag = 1 (%)                 122.7 ( 2.1)     189.8 ( 3.2)    0.037
lab_troponin_flag = 1 (%)           1600.0 (27.9)    1901.2 (32.5)   <0.001
lab_creatinine_kinase_flag = 1 (%)  2627.5 (45.8)    2964.5 (50.7)   <0.001

In [18]:
ps_matches_df <- data.table::fread(file.path(data_dir, "ps_matches_df.csv"), data.table = FALSE)

head(ps_matches_df)

  icustay_id group match
1 262436     ctrl  1
2 244460     ctrl  2
3 298177     ctrl  3
4 290165     ctrl  4
5 278397     ctrl  5
6 212022     ctrl  6

In [21]:
ps_df <- ps_matches_df %>%
left_join(full_data, by = "icustay_id") %>%
arrange(desc(group), match)

head(ps_df)

  icustay_id group match hadm_id subject_id first_careunit intime
1 228416     trtd  1     159895   5491      MICU           2151-06-29 01:18:27
2 274174     trtd  2     103722  14855      MICU           2181-09-08 23:43:13
3 214954     trtd  3     170515  54642      MICU           2176-03-11 04:58:23
4 264413     trtd  4     134244  81436      MICU           2133-03-27 16:31:37
5 214106     trtd  5     123152  74869      MICU           2150-09-05 17:50:32
6 266275     trtd  6     107556  10363      MICU           2120-06-05 11:01:07
  outtime             angus age      ⋯ lab_pco2_flag lab_creatinine_flag
1 2151-07-27 16:00:56 1     76.58225 ⋯ 1             1
2 2181-09-26 16:52:02 1     61.84390 ⋯ 1             1
3 2176-03-15 18:00:48 1     63.86507 ⋯ 1             1
4 2133-04-04 16:15:28 1     62.60148 ⋯ 0             1
5 2150-09-12 21:40:59 1     74.13371 ⋯ 1             1
6 2120-06-08 19:43:19 1     45.96256 ⋯ 0             1
  lab_potassium_flag lab_troponin_flag lab_po2_flag lab_lactate_flag echo_int
1 1                  0                 1            1                1
2 1                  0                 1            1                1
3 1                  1                 1            1                1
4 1                  0                 0            1                1
5 1                  1                 1            1                1
6 1                  0                 0            0                1
  mort_28_day_int ps        ps_weight
1 0               0.5525232 1.809879
2 0               0.3012020 3.320031
3 0               0.7982833 1.252688
4 0               0.3320492 3.011602
5 1               0.7544158 1.325529
6 0               0.2709719 3.690419

In [37]:
tab_ps <- CreateTableOne(vars = features,
                         strata = "echo",
                         data = ps_df,
                         argsNormal = list(paired = TRUE, na.action = na.omit))
tab_ps

                                    Stratified by echo
                                     0               1               p
  n                                    1626            1626
  age (mean (sd))                     66.58 (16.54)   65.84 (17.07)   NA
  gender = F (%)                        780 (48.0)      797 (49.0)    0.575
  first_careunit = MICU (%)            1274 (78.4)     1283 (78.9)    0.732
  weight (mean (sd))                  81.35 (24.69)   79.50 (23.11)   NA
  saps (mean (sd))                    20.29 (5.42)    19.80 (5.17)    NA
  sofa (mean (sd))                     5.99 (3.74)     5.55 (3.50)    NA
  elix_score (mean (sd))               9.54 (7.67)     8.82 (7.52)    NA
  vent = 1 (%)                          851 (52.3)      806 (49.6)    0.123
  vaso = 1 (%)                          531 (32.7)      507 (31.2)    0.387
  sedative = 1 (%)                      713 (43.8)      696 (42.8)    0.571
  icd_chf = 1 (%)                       468 (28.8)      315 (19.4)   <0.001
  icd_afib = 1 (%)                      448 (27.6)      404 (24.8)    0.086
  icd_renal = 1 (%)                     250 (15.4)      232 (14.3)    0.401
  icd_liver = 1 (%)                     186 (11.4)      193 (11.9)    0.743
  icd_copd = 1 (%)                      290 (17.8)      253 (15.6)    0.091
  icd_cad = 1 (%)                       215 (13.2)      214 (13.2)    1.000
  icd_stroke = 1 (%)                    143 ( 8.8)      142 ( 8.7)    1.000
  icd_malignancy = 1 (%)                407 (25.0)      409 (25.2)    0.968
  icu_adm_weekday (%)                                                 0.325
     sunday                             234 (14.4)      209 (12.9)
     monday                             212 (13.0)      223 (13.7)
     tuesday                            222 (13.7)      256 (15.7)
     wednesday                          250 (15.4)      225 (13.8)
     thursday                           237 (14.6)      236 (14.5)
     friday                             256 (15.7)      278 (17.1)
     saturday                           215 (13.2)      199 (12.2)
  icu_adm_hour (%)                                                    0.999
     0                                   70 ( 4.3)       76 ( 4.7)
     1                                   63 ( 3.9)       64 ( 3.9)
     2                                   58 ( 3.6)       63 ( 3.9)
     3                                   54 ( 3.3)       51 ( 3.1)
     4                                   43 ( 2.6)       48 ( 3.0)
     5                                   36 ( 2.2)       38 ( 2.3)
     6                                   29 ( 1.8)       26 ( 1.6)
     7                                   19 ( 1.2)       18 ( 1.1)
     8                                   25 ( 1.5)       35 ( 2.2)
     9                                   33 ( 2.0)       32 ( 2.0)
     10                                  31 ( 1.9)       33 ( 2.0)
     11                                  54 ( 3.3)       38 ( 2.3)
     12                                  50 ( 3.1)       53 ( 3.3)
     13                                  62 ( 3.8)       58 ( 3.6)
     14                                  71 ( 4.4)       72 ( 4.4)
     15                                  78 ( 4.8)       71 ( 4.4)
     16                                  94 ( 5.8)      103 ( 6.3)
     17                                  93 ( 5.7)       91 ( 5.6)
     18                                 110 ( 6.8)      117 ( 7.2)
     19                                 107 ( 6.6)      112 ( 6.9)
     20                                 127 ( 7.8)      114 ( 7.0)
     21                                 109 ( 6.7)      107 ( 6.6)
     22                                 119 ( 7.3)      113 ( 6.9)
     23                                  91 ( 5.6)       93 ( 5.7)
  vs_map_first (mean (sd))            80.13 (19.95)   80.31 (20.05)   NA
  vs_heart_rate_first (mean (sd))     94.88 (20.77)   93.88 (20.04)   NA
  vs_temp_first (mean (sd))           36.81 (1.06)    36.86 (1.85)    NA
  vs_cvp_first (mean (sd))            12.41 (19.95)   11.86 (11.63)   NA
  lab_wbc_first (mean (sd))           13.71 (15.17)   13.70 (13.84)   NA
  lab_hemoglobin_first (mean (sd))    10.56 (2.01)    10.57 (2.02)    NA
  lab_platelet_first (mean (sd))     215.31 (130.72) 216.43 (129.90)  NA
  lab_sodium_first (mean (sd))       138.75 (5.88)   138.52 (6.08)    NA
  lab_potassium_first (mean (sd))      4.12 (0.79)     4.09 (0.76)    NA
  lab_bicarbonate_first (mean (sd))   22.39 (5.67)    22.30 (5.33)    NA
  lab_chloride_first (mean (sd))     105.50 (7.14)   105.47 (7.21)    NA
  lab_bun_first (mean (sd))           34.05 (26.40)   32.41 (25.57)   NA
  lab_lactate_first (mean (sd))        2.58 (2.21)     2.47 (2.14)    NA
  lab_creatinine_first (mean (sd))     1.72 (1.68)     1.63 (1.64)    NA
  lab_ph_first (mean (sd))             7.34 (0.11)     7.35 (0.11)    NA
  lab_po2_first (mean (sd))          135.33 (98.90)  139.78 (100.24)  NA
  lab_pco2_first (mean (sd))          42.18 (13.69)   41.46 (13.81)   NA
  lab_bnp_flag = 1 (%)                   36 ( 2.2)       25 ( 1.5)    0.196
  lab_troponin_flag = 1 (%)             518 (31.9)      392 (24.1)   <0.001
  lab_creatinine_kinase_flag = 1 (%)    843 (51.8)      716 (44.0)   <0.001
                                    Stratified by echo
                                     test
  n
  age (mean (sd))
  gender = F (%)
  first_careunit = MICU (%)
  weight (mean (sd))
  saps (mean (sd))
  sofa (mean (sd))
  elix_score (mean (sd))
  vent = 1 (%)
  vaso = 1 (%)
  sedative = 1 (%)
  icd_chf = 1 (%)
  icd_afib = 1 (%)
  icd_renal = 1 (%)
  icd_liver = 1 (%)
  icd_copd = 1 (%)
  icd_cad = 1 (%)
  icd_stroke = 1 (%)
  icd_malignancy = 1 (%)
  icu_adm_weekday (%)
     sunday
     monday
     tuesday
     wednesday
     thursday
     friday
     saturday
  icu_adm_hour (%)
     0
     1
     2
     3
     4
     5
     6
     7
     8
     9
     10
     11
     12
     13
     14
     15
     16
     17
     18
     19
     20
     21
     22
     23
  vs_map_first (mean (sd))
  vs_heart_rate_first (mean (sd))
  vs_temp_first (mean (sd))
  vs_cvp_first (mean (sd))
  lab_wbc_first (mean (sd))
  lab_hemoglobin_first (mean (sd))
  lab_platelet_first (mean (sd))
  lab_sodium_first (mean (sd))
  lab_potassium_first (mean (sd))
  lab_bicarbonate_first (mean (sd))
  lab_chloride_first (mean (sd))
  lab_bun_first (mean (sd))
  lab_lactate_first (mean (sd))
  lab_creatinine_first (mean (sd))
  lab_ph_first (mean (sd))
  lab_po2_first (mean (sd))
  lab_pco2_first (mean (sd))
  lab_bnp_flag = 1 (%)
  lab_troponin_flag = 1 (%)
  lab_creatinine_kinase_flag = 1 (%)

In [35]:
capture.output(tab_ps_df <- tab_ps %>%
               print(smd = TRUE) %>%
               as.data.frame(stringsAsFactors = FALSE) %>%
               select(-test)) %>% invisible

In [36]:
tab_ps_df

                                   0               1               p
n                                    1626            1626
age (mean (sd))                     66.58 (16.54)   65.84 (17.07)   NA
gender = F (%)                        780 (48.0)      797 (49.0)    0.575
first_careunit = MICU (%)            1274 (78.4)     1283 (78.9)    0.732
weight (mean (sd))                  81.35 (24.69)   79.50 (23.11)   NA
saps (mean (sd))                    20.29 (5.42)    19.80 (5.17)    NA
sofa (mean (sd))                     5.99 (3.74)     5.55 (3.50)    NA
elix_score (mean (sd))               9.54 (7.67)     8.82 (7.52)    NA
vent = 1 (%)                          851 (52.3)      806 (49.6)    0.123
vaso = 1 (%)                          531 (32.7)      507 (31.2)    0.387
sedative = 1 (%)                      713 (43.8)      696 (42.8)    0.571
icd_chf = 1 (%)                       468 (28.8)      315 (19.4)   <0.001
icd_afib = 1 (%)                      448 (27.6)      404 (24.8)    0.086
icd_renal = 1 (%)                     250 (15.4)      232 (14.3)    0.401
icd_liver = 1 (%)                     186 (11.4)      193 (11.9)    0.743
icd_copd = 1 (%)                      290 (17.8)      253 (15.6)    0.091
icd_cad = 1 (%)                       215 (13.2)      214 (13.2)    1.000
icd_stroke = 1 (%)                    143 ( 8.8)      142 ( 8.7)    1.000
icd_malignancy = 1 (%)                407 (25.0)      409 (25.2)    0.968
icu_adm_weekday (%)                                                 0.325
   sunday                             234 (14.4)      209 (12.9)
   monday                             212 (13.0)      223 (13.7)
   tuesday                            222 (13.7)      256 (15.7)
   wednesday                          250 (15.4)      225 (13.8)
   thursday                           237 (14.6)      236 (14.5)
   friday                             256 (15.7)      278 (17.1)
   saturday                           215 (13.2)      199 (12.2)
icu_adm_hour (%)                                                    0.999
   0                                   70 ( 4.3)       76 ( 4.7)
   1                                   63 ( 3.9)       64 ( 3.9)
⋮                                  ⋮               ⋮               ⋮
   14                                  71 ( 4.4)       72 ( 4.4)
   15                                  78 ( 4.8)       71 ( 4.4)
   16                                  94 ( 5.8)      103 ( 6.3)
   17                                  93 ( 5.7)       91 ( 5.6)
   18                                 110 ( 6.8)      117 ( 7.2)
   19                                 107 ( 6.6)      112 ( 6.9)
   20                                 127 ( 7.8)      114 ( 7.0)
   21                                 109 ( 6.7)      107 ( 6.6)
   22                                 119 ( 7.3)      113 ( 6.9)
   23                                  91 ( 5.6)       93 ( 5.7)
vs_map_first (mean (sd))            80.13 (19.95)   80.31 (20.05)   NA
vs_heart_rate_first (mean (sd))     94.88 (20.77)   93.88 (20.04)   NA
vs_temp_first (mean (sd))           36.81 (1.06)    36.86 (1.85)    NA
vs_cvp_first (mean (sd))            12.41 (19.95)   11.86 (11.63)   NA
lab_wbc_first (mean (sd))           13.71 (15.17)   13.70 (13.84)   NA
lab_hemoglobin_first (mean (sd))    10.56 (2.01)    10.57 (2.02)    NA
lab_platelet_first (mean (sd))     215.31 (130.72) 216.43 (129.90)  NA
lab_sodium_first (mean (sd))       138.75 (5.88)   138.52 (6.08)    NA
lab_potassium_first (mean (sd))      4.12 (0.79)     4.09 (0.76)    NA
lab_bicarbonate_first (mean (sd))   22.39 (5.67)    22.30 (5.33)    NA
lab_chloride_first (mean (sd))     105.50 (7.14)   105.47 (7.21)    NA
lab_bun_first (mean (sd))           34.05 (26.40)   32.41 (25.57)   NA
lab_lactate_first (mean (sd))        2.58 (2.21)     2.47 (2.14)    NA
lab_creatinine_first (mean (sd))     1.72 (1.68)     1.63 (1.64)    NA
lab_ph_first (mean (sd))             7.34 (0.11)     7.35 (0.11)    NA
lab_po2_first (mean (sd))          135.33 (98.90)  139.78 (100.24)  NA
lab_pco2_first (mean (sd))          42.18 (13.69)   41.46 (13.81)   NA
lab_bnp_flag = 1 (%)                   36 ( 2.2)       25 ( 1.5)    0.196
lab_troponin_flag = 1 (%)             518 (31.9)      392 (24.1)   <0.001
lab_creatinine_kinase_flag = 1 (%)    843 (51.8)      716 (44.0)   <0.001
                                   SMD
n
age (mean (sd))                     0.044
gender = F (%)                      0.021
first_careunit = MICU (%)           0.014
weight (mean (sd))                  0.077
saps (mean (sd))                    0.092
sofa (mean (sd))                    0.123
elix_score (mean (sd))              0.096
vent = 1 (%)                        0.055
vaso = 1 (%)                        0.032
sedative = 1 (%)                    0.021
icd_chf = 1 (%)                     0.221
icd_afib = 1 (%)                    0.062
icd_renal = 1 (%)                   0.031
icd_liver = 1 (%)                   0.013
icd_copd = 1 (%)                    0.061
icd_cad = 1 (%)                     0.002
icd_stroke = 1 (%)                  0.002
icd_malignancy = 1 (%)              0.003
icu_adm_weekday (%)                 0.093
   sunday
   monday
   tuesday
   wednesday
   thursday
   friday
   saturday
icu_adm_hour (%)                    0.098
   0
   1
⋮                                  ⋮
   14
   15
   16
   17
   18
   19
   20
   21
   22
   23
vs_map_first (mean (sd))            0.009
vs_heart_rate_first (mean (sd))     0.049
vs_temp_first (mean (sd))           0.031
vs_cvp_first (mean (sd))            0.033
lab_wbc_first (mean (sd))           0.001
lab_hemoglobin_first (mean (sd))    0.009
lab_platelet_first (mean (sd))      0.009
lab_sodium_first (mean (sd))        0.039
lab_potassium_first (mean (sd))     0.033
lab_bicarbonate_first (mean (sd))   0.018
lab_chloride_first (mean (sd))      0.004
lab_bun_first (mean (sd))           0.063
lab_lactate_first (mean (sd))       0.049
lab_creatinine_first (mean (sd))    0.053
lab_ph_first (mean (sd))            0.086
lab_po2_first (mean (sd))           0.045
lab_pco2_first (mean (sd))          0.053
lab_bnp_flag = 1 (%)                0.050
lab_troponin_flag = 1 (%)           0.173
lab_creatinine_kinase_flag = 1 (%)  0.157

In [ ]:
wtd_pval <- tab_wtd_df %>%
setNames(c("trtd", "ctrl", "pval")) %>%
mutate(cov = rownames(.)) %>%
mutate_all(funs(str_replace_all(., "\\s+$|^\\s+", ""))) %>%
mutate(cov = strsplit(cov, " ") %>% map_chr(first)) %>%
filter(!is.null(pval) & !is.na(pval) & pval != "") %>%
mutate(pval = str_replace_all(pval, "<", "")) %>%
mutate(pval = as.numeric(pval)) %>%
select(cov, pval)

wtd_pval

In [ ]:
tab_fmt <- tab_df %>%
setNames(c("ctrl", "trtd", "pval", "smd")) %>%
mutate(cov = rownames(.)) %>%
mutate(ctrl = ifelse((grepl("%", cov) & grepl("=", cov)) | grepl("^\\s+", cov),
                     str_extract(ctrl, "\\((.*?)\\)") %>% str_replace_all("\\(|\\)", "") %>% sprintf("%s%%", .),
                     ctrl)) %>%
mutate(trtd = ifelse((grepl("%", cov) & grepl("=", cov)) | grepl("^\\s+", cov),
                     str_extract(trtd, "\\((.*?)\\)") %>% str_replace_all("\\(|\\)", "") %>% sprintf("%s%%", .),
                     trtd)) %>%
select(cov, ctrl, trtd, pval, smd)

tab_fmt

In [ ]:
tab_ps_fmt <- tab_ps_df %>%
setNames(c("ctrl", "trtd", "pval", "smd")) %>%
mutate(cov = rownames(.)) %>%
mutate(ctrl = ifelse((grepl("%", cov) & grepl("=", cov)) | grepl("^\\s+", cov),
                     str_extract(ctrl, "\\((.*?)\\)") %>% str_replace_all("\\(|\\)", "") %>% sprintf("%s%%", .),
                     ctrl)) %>%
mutate(trtd = ifelse((grepl("%", cov) & grepl("=", cov)) | grepl("^\\s+", cov),
                     str_extract(trtd, "\\((.*?)\\)") %>% str_replace_all("\\(|\\)", "") %>% sprintf("%s%%", .),
                     trtd)) %>%
select(cov, ctrl, trtd, pval, smd)

tab_ps_fmt

In [ ]:
tab_wtd_fmt <- tab_wtd_df %>%
setNames(c("ctrl", "trtd", "pval")) %>%
mutate(cov = rownames(.)) %>%
mutate(ctrl = ifelse((grepl("%", cov) & grepl("=", cov)) | grepl("^\\s+", cov),
                     str_extract(ctrl, "\\((.*?)\\)") %>% str_replace_all("\\(|\\)", "") %>% sprintf("%s%%", .),
                     ctrl)) %>%
mutate(trtd = ifelse((grepl("%", cov) & grepl("=", cov)) | grepl("^\\s+", cov),
                     str_extract(trtd, "\\((.*?)\\)") %>% str_replace_all("\\(|\\)", "") %>% sprintf("%s%%", .),
                     trtd)) %>%
select(cov, ctrl, trtd, pval)

tab_wtd_fmt

In [ ]:
tab_full <-
tab_fmt %>%
full_join(tab_wtd_fmt, by = "cov") %>%
full_join(tab_ps_fmt, by = "cov")

tab_full

In [ ]:
tab_full_fmt <-
tab_fmt %>%
setNames(c("cov", "Non-Echo", "Echo", "p value", "SMD")) %>%
full_join(tab_wtd_fmt %>%
          setNames(c("cov", "Non-Echo (weighted cohort)", "Echo (weighted cohort)",
                     "p value (weighted cohort)")), by = "cov") %>%
full_join(tab_ps_fmt %>%
          setNames(c("cov", "Non-Echo (PS matching)", "Echo (PS matching)",
                     "p value (PS matching)", "SMD (PS matching)")), by = "cov") %>%
mutate_all(funs(str_replace_all(., "\\s+$|^\\s+", ""))) %>%
mutate(cov_ = strsplit(cov, " ") %>% map_chr(first)) %>%
mutate(cov = str_replace_all(cov_, "_", " ")) %>%
mutate(cov = str_replace_all(cov, "lab|vs|flag|icd|first", "")) %>%
mutate_all(funs(str_replace_all(., "\\s+$|^\\s+", ""))) %>%
mutate(cov = case_when(
    grepl("icd|vs|lab|day", cov_) ~ toupper(cov),
    TRUE ~ tools::toTitleCase(cov)
)) %>%
mutate(cov = case_when(
    cov == "Gender" ~ "Gender (Female)",
    cov == "Careunit" ~ "Service Unit (MICU vs SICU)",
    cov == "Weight" ~ "Weight (Kg)",
    cov == "Elix Score" ~ "Elixhauser Score",
    cov == "Saps" ~ "SAPS Score",
    cov == "Sofa" ~ "SOFA Score",
    cov == "Vent" ~ "Mechanical Ventilation Use (1st 24 Hours)",
    cov == "Vaso" ~ "Vasopressor Use (1st 24 Hours)",
    cov == "Sedative" ~ "Sedative Use (1st 24 Hours)",
    cov == "ICU ADM WEEKDAY" ~ "Day of ICU Admission",
    cov == "TEMP" ~ "Temperature (C)",
    cov == "HEART RATE" ~ "Heart Rate",
    cov %in% c("TROPONIN", "BNP", "CREATININE KINASE") ~ paste(cov, "(tested)"),
    TRUE ~ cov
)) %>%
select(-cov_) %>%
rename(Covariate = cov)

tab_full_fmt

In [ ]:
data.table::fwrite(tab_full_fmt, file.path(data_dir, "tableone_full.csv"))
data.table::fwrite(tab_full, file.path(data_dir, "tableone_raw.csv"))
data.table::fwrite(wtd_pval, file.path(data_dir, "wtd_pval.csv"))